# Generated by Django 3.0.8 on 2020-07-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvesteeTeamMemberProfile',
            new_name='Details',
        ),
    ]
