# Generated by Django 3.0.8 on 2020-07-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapi', '0002_auto_20200720_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
